name: products
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  shared_preferences: ^2.1.0
  path_provider: ^2.0.15
  fluttertoast: ^8.2.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/brands.json
    - assets/categories.json
    - assets/products.json
    - assets/tire.png
    - assets/images/



